name: GitHub Event Context
description: Collect conformed information on the workflow event context.
author: CPC Systems
branding:
  icon: info
  color: green
runs:
  using: node24
  main: dist/index.js
outputs:
  sha:
    description: The SHA of the source commit.
  url:
    description: A GitHub URL pointing to location that makes sense given the contents of the title output.
  artifact-path:
    description: |
      A path that includes the repository name as well as event context in an appropriate form to specify where to store generated artifacts at.
      Never has a leading '/' character (no prefix).
      Always has a trailing '/' character (suffix).
      Example: "Railway-UK-DataModels/main/".
  title:
    description: A label for the event context.
  build-metadata:
    description: |
      A string compatible with the constraints of SemVer build metadata (alphanumerics and hypens only, [0-9A-Za-z-]).
      Examples: "tag-v-1-2-0" (tag), "PR123-d0b00a8" (pull request), "d0b00a8" (default branch).
      See: https://semver.org/#spec-item-10
