name: Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .tool-versions

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check that Package runs
        run: npm run package
